import { KiwiConfig } from '@lib/config/config.types';

const DEFAULT_CONFIG: KiwiConfig = {
  associations: {
    git: [
      'am',
      'archive',
      'bisect',
      'branch',
      'bundle',
      'checkout',
      'cherry-pick',
      'citool',
      'clean',
      'clone',
      'commit',
      'describe',
      'diff',
      'fetch',
      'format-patch',
      'gc',
      'grep',
      'gui',
      'log',
      'maintenance',
      'merge',
      'mv',
      'notes',
      'pull',
      'push',
      'range-diff',
      'rebase',
      'reset',
      'restore',
      'revert',
      'rm',
      'shortlog',
      'show',
      'sparse-checkout',
      'stash',
      'status',
      'submodule',
      'switch',
      'tag',
      'worktree'
    ],
    ng: [
      'analytics',
      'build',
      'cache',
      'completion',
      'deploy',
      'doc',
      'e2e',
      'extract-i18n',
      'generate',
      'lint',
      'serve',
      'test',
    ]
  },
  aliases: {
    g: 'generate',
    b: 'build',
    s: 'serve',
    t: 'test',
    e: 'e2e',
    d: 'deploy',
    l: 'lint',
  }
}
export default DEFAULT_CONFIG;